Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrailheadEntityUpdate__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>New value of trailheadapp__Icon__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>New value of trailheadapp__Products__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Description__c</fullName>
            </value>
            <value>
                <fullName>Icon__c</fullName>
            </value>
            <value>
                <fullName>Level__c</fullName>
            </value>
            <value>
                <fullName>Name__c</fullName>
            </value>
            <value>
                <fullName>Products__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>URL__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrailheadEntityUpdateEvent__e/TrailheadEntityUpdateEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event fired when the values of one or more watched fields on a Badge or Trail is updated.</description>
    <label>Trailhead Entity Update Event</label>
    <pluralLabel>Trailhead Entity Update Events</pluralLabel>
</CustomObject>

Core/objects/TrailheadEntityUpdateEvent__e/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/classes/tests/TrailheadEntityUpdateEvtTgrHdlr_Tests.cls
@isTest(isParallel=true)
private class TrailheadEntityUpdateEvtTgrHdlr_Tests {
    @isTest
    private static void it_should_insert_trailhead_entity_updates() {
        TrailheadEntityUpdateEventTS teueGenerator = new TrailheadEntityUpdateEventTS(
            new Map<String, Object>{'generatorReturnValue' => 'all'},
            new List<TestSupport.TestDataField>{
                new TestSupport.TestDataField(TrailheadEntityUpdateEvent__e.Products__c, 'New products.')
            }
        );
        teueGenerator.generate();
        List<sObject> testEvents = teueGenerator
            .setFieldSpec(new TestSupport.TestDataField(TrailheadEntityUpdateEvent__e.Icon__c, 'www.testicon.com'))
            .generate();
        
        Test.startTest();
        EventBus.publish(testEvents);
        Test.stopTest();

        List<TrailheadEntityUpdate__c> productUpdates = [
            SELECT Id
            FROM TrailheadEntityUpdate__c
            WHERE Products__c = 'New products.' AND Icon__c = null AND UpdatedFields__c = 'Products__c'
        ];
        List<TrailheadEntityUpdate__c> productAndIconUpdates = [
            SELECT Id 
            FROM TrailheadEntityUpdate__c 
            WHERE Products__c = 'New products.' AND Icon__c = 'www.testicon.com' AND UpdatedFields__c='Icon__c;Products__c'
        ];
        Assert.areEqual(200, productUpdates.size(), 'Expected 200 records for entities updates to the Products field only.');
        Assert.areEqual(200, productAndIconUpdates.size(), 'Expected 200 records for entities updates to the Products and Icon fields.');
    }
}