Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityUpdate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>New value of trailheadapp__Description__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>trailheadapp__Badge__c</fullName>
            </value>
            <value>
                <fullName>trailheadapp__Trail__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrailheadEntityUpdate__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>New value of trailheadapp__Icon__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>New value of trailheadapp__Level__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foundational</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>New value of Name on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>New value of trailheadapp__Products__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>New value of trailheadapp__Type__c on trailheadapp__Badge__c.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>New value of trailheadapp__URL__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

Core/classes/tests/BatchTrailheadEntityUpdateSync_Tests.cls
@isTest
private class BatchTrailheadEntityUpdateSync_Tests {
    @isTest
    private static void it_should_not_make_callout_without_existing_updates() {
        Test.startTest();
        Database.executeBatch(new BatchTrailheadEntityUpdateSync());
        Test.stopTest();

        Assert.areEqual(0, Limits.getCallouts(), 'Did not expect callout to be made when there are no TrailheadEntityUpdate__c records.');
        Assert.areEqual(0, Limits.getDmlStatements(), 'Did not expect DML statements from BatchTrailheadEntityUpdateSync when there are no TrailheadEntityUpdate__c records.');
    }

    @isTest
    private static void it_should_delete_records_after_successful_callout() {
        TrailheadEntityUpdateTS trailheadEntityUpdateGenerator = new TrailheadEntityUpdateTS(
            new Map<String, Object>{'generateRecordIDs' => false, 'numberToGenerate' => 40, 'generatorReturnValue' => 'all'},
            new List<TestSupport.TestDataField>{
                new CounterSuffixField(TrailheadEntityUpdate__c.Name__c, 'Test Trail '),
                new TestSupport.TestDataField(TrailheadEntityUpdate__c.Description__c, 'Updated description.'),
                new TestSupport.TestDataField(TrailheadEntityUpdate__c.EntityType__c, 'trailheadapp__Trail__c')
            }
        );
        trailheadEntityUpdateGenerator.generate();
        trailheadEntityUpdateGenerator.setFieldSpec(new TestSupport.TestDataField(TrailheadEntityUpdate__c.Icon__c, 'www.updatedicon.com')).generate();
        trailheadEntityUpdateGenerator.setFieldSpec(new RandomPicklistValueField(TrailheadEntityUpdate__c.Level__c)).generate();
        trailheadEntityUpdateGenerator.overwriteFieldSpecs(new List<TestSupport.TestDataField>{
            new CounterSuffixField(TrailheadEntityUpdate__c.Name__c, 'Test Badge '),
            new TestSupport.TestDataField(TrailheadEntityUpdate__c.EntityType__c, 'trailheadapp__Badge__c'),
            new RandomPicklistValueField(TrailheadEntityUpdate__c.Type__c)
        }).generate();
        trailheadEntityUpdateGenerator.setFieldSpec(new TestSupport.TestDataField(TrailheadEntityUpdate__c.Products__c, 'Updated products.')).generate();

        insert trailheadEntityUpdateGenerator.setFieldSpec(new TestSupport.TestDataField(TrailheadEntityUpdate__c.URL__c, 'www.updatedurl.com')).generate();
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CustomHttpCalloutMock('', 204));
        Database.executeBatch(new BatchTrailheadEntityUpdateSync(), trailheadEntityUpdateGenerator.records.size());
        Test.stopTest();
        
        List<LogEntry__c> logEntries = [
            SELECT Id, Message__c 
            FROM LogEntry__c 
            WHERE 
                OriginSourceActionName__c = 'finish' 
                AND OriginSourceAPIName__c = 'BatchTrailheadEntityUpdateSync' 
                AND OriginSourceMetadataType__c = 'ApexClass' 
                AND LoggingLevel__c = 'INFO'
        ];

        Assert.areEqual(
            0, 
            [SELECT COUNT() FROM TrailheadEntityUpdate__c],
            'Expected all TrailheadEntityUpdate__c records to be deleted by BatchTrailheadEntityUpdateSync after successful callout.'
        );
        Assert.areEqual(1, logEntries.size(), 'Expected info debug log from BatchTrailheadEntityUpdateSync.finish().');
        Assert.areEqual(
            String.format('Successfully updated {0} Trailhead Entities.', new List<Object>{trailheadEntityUpdateGenerator.records.size()}),
            logEntries[0].Message__c,
            'Expected info debug log from BatchTrailheadEntityUpdateSync.finish().'
        );
    }

    @isTest
    private static void it_should_log_callout_errors() {
        String testResponseBody = '{"error": "Test internal error."}';
        String testStatus = 'Internal Server Error';
        Integer testStatusCode = 500;

        TrailheadEntityUpdateTS trailheadEntityUpdateGenerator = new TrailheadEntityUpdateTS(
            new Map<String, Object>{'generateRecordIDs' => false},
            new List<TestSupport.TestDataField>{
                new CounterSuffixField(TrailheadEntityUpdate__c.Name__c, 'Test Trail '),
                new TestSupport.TestDataField(TrailheadEntityUpdate__c.Description__c, 'Updated description.')
            }
        );
        insert trailheadEntityUpdateGenerator.generate();

        Test.setMock(HttpCalloutMock.class, new CustomHttpCalloutMock(testResponseBody, testStatusCode, testStatus));

        Test.startTest();
        Database.executeBatch(new BatchTrailheadEntityUpdateSync(), trailheadEntityUpdateGenerator.records.size());
        Test.stopTest();

        List<LogEntry__c> logEntries = [
            SELECT Id, Message__c 
            FROM LogEntry__c 
            WHERE 
                OriginSourceActionName__c = 'execute' 
                AND OriginSourceAPIName__c = 'BatchTrailheadEntityUpdateSync' 
                AND OriginSourceMetadataType__c = 'ApexClass' 
                AND LoggingLevel__c = 'ERROR'
        ];  
        Assert.areEqual(1, logEntries.size(), 'Expected error debug log from BatchTrailheadEntityUpdateSync.execute().');
        Assert.isTrue(logEntries[0].Message__c.startsWith('Error with callout to Recommended Badges.'), 'Expected error debug log from BatchTrailheadEntityUpdateSync.execute().');
        Assert.isTrue(logEntries[0].Message__c.contains(testResponseBody), 'Expected error debug log from BatchTrailheadEntityUpdateSync.execute().');
        Assert.isTrue(logEntries[0].Message__c.contains(testStatus), 'Expected error debug log from BatchTrailheadEntityUpdateSync.execute().');
        Assert.isTrue(logEntries[0].Message__c.contains(String.valueOf(testStatusCode)), 'Expected error debug log from BatchTrailheadEntityUpdateSync.execute().');
    }
}