Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityUpdate__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c. Used as an external ID field for integration.</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Archived__c.field-meta.xml
<CustomField>
    <fullName>Archived__c</fullName>
    <description>New value of trailheadapp__Archived__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Archived</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>New value of trailheadapp__Description__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>trailheadapp__Badge__c</fullName>
            </value>
            <value>
                <fullName>trailheadapp__Trail__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrailheadEntityUpdate__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>New value of trailheadapp__Icon__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>New value of trailheadapp__Level__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Foundational</fullName>
            </value>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>New value of Name on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>New value of trailheadapp__Products__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>New value of trailheadapp__Type__c on trailheadapp__Badge__c.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Superbadge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Description__c</fullName>
            </value>
            <value>
                <fullName>Icon__c</fullName>
            </value>
            <value>
                <fullName>Level__c</fullName>
            </value>
            <value>
                <fullName>Name__c</fullName>
            </value>
            <value>
                <fullName>Products__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>URL__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>New value of trailheadapp__URL__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>URL</label>
    <type>Url</type>
</CustomField>

Core/classes/BatchTrailheadEntityUpdateSync.cls
/**
 * Batch Apex job to make callout to Recommended Badges org with details of changes to trailheadapp__Badge__c and trailheadapp__Trail__c records.
 * @author Ben Learn
 * @since 06-01-2023
 * @group Core
 */
public without sharing class BatchTrailheadEntityUpdateSync implements Database.Batchable<sObject>, Database.AllowsCallouts {
    private static final String BADGE_ENTITY_TYPE = 'trailheadapp__Badge__c';
    private static final String TRAIL_ENTITY_TYPE = 'trailheadapp__Trail__c';
    private static final Map<String, String> nameFieldByEntityType = new Map<String, String>{BADGE_ENTITY_TYPE => 'BadgeName__c', TRAIL_ENTITY_TYPE => 'TrailName__c'};
    
    /**
     * Returns all TrailheadEntityUpdate__c records in org. 
     * @param bc BatchableContext for ongoing Apex batch job.
     * @return  `Database.QueryLocator`
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT APIName__c, Archived__c, Description__c, EntityType__c, Icon__c, Level__c, Name__c, Products__c, Type__c, UpdatedFields__c, URL__c FROM TrailheadEntityUpdate__c'
        );
    }

    /**
     * Makes callout to Recommended Badges org with details of changed trailheadapp__Badge__c and trailheadapp__Trail__c records. Hard deletes corresponding Trailhead Entity 
     * Update records if successful.
     * @param bc Batchable context for ongoing Apex batch job.
     * @param trailheadEntityUpdates Trailhead Entity Update records for current batch. 
     */    
    public void execute(Database.BatchableContext bc, List<TrailheadEntityUpdate__c> trailheadEntityUpdates) {
        Map<String, Map<String, Object>> updatedBadgesByAPIName = new Map<String, Map<String, Object>>();
        Map<String, Map<String, Object>> updatedTrailsByAPIName = new Map<String, Map<String, Object>>();
        
        Map<String, Object> updatedTrailheadEntity;
        for(TrailheadEntityUpdate__c teu : trailheadEntityUpdates) {
            updatedTrailheadEntity = new Map<String, Object>();
            for(String updatedField : teu.UpdatedFields__c.split(';')) {
                if(updatedField == 'Name__c') {
                    updatedTrailheadEntity.put(nameFieldByEntityType.get(teu.EntityType__c), teu.get(updatedField));
                } else {
                    updatedTrailheadEntity.put(updatedField, teu.get(updatedField));
                }
            }
            if(teu.EntityType__c == BADGE_ENTITY_TYPE) {
                updatedBadgesByAPIName.put(teu.APIName__c, updatedTrailheadEntity);
            } else if(teu.EntityType__c == TRAIL_ENTITY_TYPE) {
                updatedTrailsByAPIName.put(teu.APIName__c, updatedTrailheadEntity);
            }
        }

        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:RecommendedBadges/services/apexrest/TrailheadEntities/');
        request.setMethod('PATCH');
        request.setHeader('Content-Type', 'application/json');
        request.setBody('{"updatedBadgesByAPIName": ' + JSON.serialize(updatedBadgesByAPIName) + ', "updatedTrailsByAPIName": ' + JSON.serialize(updatedTrailsByAPIName) + '}');
        System.debug(request.getBody());
        HttpResponse response = new Http().send(request);

        if(response.getStatusCode() == 204) {
            Database.delete(trailheadEntityUpdates);
            Database.emptyRecycleBin(trailheadEntityUpdates);
        } else {
            // log error
            // also give logs of how many updated
        }
    }

    /**
     * 
     * @param bc Batchable context for ongoing Apex batch job.
     */    
    public void finish(Database.BatchableContext bc) {

    }
}