Core/objects/TrailheadEntityDelete__c/TrailheadEntityDelete__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store information about Badges/Trails that are being archived.</description>
    <label>Trailhead Entity Delete</label>
    <nameField>
        <displayFormat>TED-{0000}</displayFormat>
        <label>Trailhead Entity Delete NumberName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Deletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityDelete__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntityType</valueSetName>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityEvent__e/TrailheadEntityEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event fired when a the values of one or more tracked fields on a Badge or Trail is updated.</description>
    <label>Trailhead Entity Event</label>
    <pluralLabel>Trailhead Entity Events</pluralLabel>
</CustomObject>

Core/objects/TrailheadEntityEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that event corresponds to.</description>
    <label>Entity Type</label>
    <length>22</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>New value of trailheadapp__Icon__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of operation to perform with changes to Trailhead entity.</description>
    <label>Operation</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>New value of trailheadapp__Products__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Products</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityUpdate__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c. Used as an external ID field for integration.</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>trailheadapp__Badge__c</fullName>
            </value>
            <value>
                <fullName>trailheadapp__Trail__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrailheadEntityUpdate__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>New value of trailheadapp__Icon__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Icon</label>
    <type>Url</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>New value of trailheadapp__Products__c on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Description__c</fullName>
            </value>
            <value>
                <fullName>Icon__c</fullName>
            </value>
            <value>
                <fullName>Level__c</fullName>
            </value>
            <value>
                <fullName>Name__c</fullName>
            </value>
            <value>
                <fullName>Products__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>URL__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/globalValueSets/EntityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>trailheadapp__Badge__c</fullName>
    </customValue>
    <customValue>
        <fullName>trailheadapp__Trail__c</fullName>
    </customValue>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record corresponds to.</description>
    <masterLabel>Entity Type</masterLabel>
</GlobalValueSet>

Core/classes/tests/TrailheadEntityEventTriggerHandler_Tests.cls
@isTest(isParallel=true)
private class TrailheadEntityEventTriggerHandler_Tests {
    @isTest
    private static void it_should_insert_trailhead_entity_updates() {
        TrailheadEntityEventTS eventGenerator = new TrailheadEntityEventTS(
            new Map<String, Object>{'generatorReturnValue' => 'all'},
            new List<TestSupport.TestDataField>{
                new TestSupport.TestDataField(TrailheadEntityEvent__e.Operation__c, 'update'),
                new TestSupport.TestDataField(TrailheadEntityEvent__e.Products__c, 'New products.')
            }
        );
        eventGenerator.generate();
        List<sObject> testEvents = eventGenerator
            .setFieldSpec(new TestSupport.TestDataField(TrailheadEntityEvent__e.Icon__c, 'www.testicon.com'))
            .generate();
        
        Test.startTest();
        EventBus.publish(testEvents);
        Test.stopTest();

        List<TrailheadEntityUpdate__c> productUpdates = [
            SELECT Id
            FROM TrailheadEntityUpdate__c
            WHERE Products__c = 'New products.' AND Icon__c = null AND UpdatedFields__c = 'Products__c'
        ];
        List<TrailheadEntityUpdate__c> productAndIconUpdates = [
            SELECT Id 
            FROM TrailheadEntityUpdate__c 
            WHERE Products__c = 'New products.' AND Icon__c = 'www.testicon.com' AND UpdatedFields__c='Icon__c;Products__c'
        ];
        Assert.areEqual(200, productUpdates.size(), 'Expected 200 records for entities updates to the Products field only.');
        Assert.areEqual(200, productAndIconUpdates.size(), 'Expected 200 records for entities updates to the Products and Icon fields.');
    }

    @isTest
    private static void it_should_insert_trailhead_entity_deletes() {
        TrailheadEntityEventTS eventGenerator = new TrailheadEntityEventTS(
            new Map<String, Object>{'generatorReturnValue' => 'all'},
            new List<TestSupport.TestDataField>{new TestSupport.TestDataField(TrailheadEntityEvent__e.Operation__c, 'delete')}
        );
        List<sObject> testEvents = eventGenerator.generate();
    
        Test.startTest();
        EventBus.publish(testEvents);
        Test.stopTest();

        Set<String> eventAPINames = eventGenerator.eventsByAPIName.keySet();
        List<TrailheadEntityDelete__c> deletes = [
            SELECT Id, APIName__c, EntityType__c
            FROM TrailheadEntityDelete__c
            WHERE APIName__c IN :eventAPINames
        ];
        Assert.areEqual(200, deletes.size(), 'Expected one Trailhead Entity Delete record for each Trailhead Entity Event.');
        for(TrailheadEntityDelete__c d : deletes) {
            Assert.areEqual(
                d.EntityType__c, 
                eventGenerator.eventsByAPIName.get(d.APIName__c).get('EntityType__c'), 
                'Expected entity type of Trailhead Delete to match entity type of Traihlead Event.'
            );
        }
    }
}