Core/objects/TrailheadEntityDelete__c/TrailheadEntityDelete__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store information about Badges/Trails that are being archived.</description>
    <label>Trailhead Entity Delete</label>
    <nameField>
        <displayFormat>TED-{0000}</displayFormat>
        <label>Trailhead Entity Delete NumberName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Deletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityDelete__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntityType</valueSetName>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityEvent__e/TrailheadEntityEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event fired when a the values of one or more tracked fields on a Badge or Trail is updated.</description>
    <label>Trailhead Entity Event</label>
    <pluralLabel>Trailhead Entity Events</pluralLabel>
</CustomObject>

Core/objects/TrailheadEntityEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that event corresponds to.</description>
    <label>Entity Type</label>
    <length>22</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of operation to perform with changes to Trailhead entity.</description>
    <label>Operation</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityUpdate__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c. Used as an external ID field for integration.</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>trailheadapp__Badge__c</fullName>
            </value>
            <value>
                <fullName>trailheadapp__Trail__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/globalValueSets/EntityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>trailheadapp__Badge__c</fullName>
    </customValue>
    <customValue>
        <fullName>trailheadapp__Trail__c</fullName>
    </customValue>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record corresponds to.</description>
    <masterLabel>Entity Type</masterLabel>
</GlobalValueSet>

Core/classes/TrailheadEntityEventTriggerHandler.cls
/**
 * Trigger handler for the TrailheadEntityEvent__e platform event
 * @author Ben Learn
 * @since 06-02-2023
 * @group Core
 */
public without sharing class TrailheadEntityEventTriggerHandler extends TriggerHandler {
    private static final List<String> systemPlatformEventFields {
        get {
            if(systemPlatformEventFields == null) {
                systemPlatformEventFields = new List<String>{'CreatedById', 'CreatedDate', 'EventUuid', 'ReplayId'};
            }
            return systemPlatformEventFields;
        }
        set;
    }

    /**
     * Constructor for trigger handler
     */
    public TrailheadEntityEventTriggerHandler() {
        super();
    }


    /**
     * 
     * @param newRecordsMap Map of IDs to newly inserted TrailheadEntityEvent__e events
     */
    protected override void afterInsert(Map<Id, sObject> newRecordsMap) {
        List<TrailheadEntityEvent__e> events = (List<TrailheadEntityEvent__e>) newRecordsMap.values();
        List<TrailheadEntityUpdate__c> trailheadEntityUpdates = new List<TrailheadEntityUpdate__c>();
        List<TrailheadEntityDelete__c> trailheadEntityDeletes = new List<TrailheadEntityDelete__c>();

        for(TrailheadEntityEvent__e ev : events) {
            if(ev.Operation__c == 'delete') {
                TrailheadEntityDelete__c ted = new TrailheadEntityDelete__c(
                    APIName__c = ev.APIName__c, EntityType__c = ev.EntityType__c
                );
                trailheadEntityDeletes.add(ted);
            } else if(ev.Operation__c == 'update') {
                Map<String, Object> populatedFieldsMap = ev.getPopulatedFieldsAsMap();
                TrailheadEntityUpdate__c teu = new TrailheadEntityUpdate__c();
                Set<String> updatedFields = new Set<String>();
                
                for(String populatedField : populatedFieldsMap.keySet()) {
                    if(systemPlatformEventFields.contains(populatedField) == false && populatedField != 'Operation__c') { // temp operation ignored
                        teu.put(populatedField, populatedFieldsMap.get(populatedField));
                    }
                }
                trailheadEntityUpdates.add(teu);
            }
        }

        List<Database.SaveResult> saveResults;
        if(trailheadEntityUpdates.size() > 0) {
            saveResults = Database.insert(trailheadEntityUpdates, false);
            DMLUtils.logErrors(saveResults, 'TrailheadEntityEventTriggerHandler');
        }
        if(trailheadEntityDeletes.size() > 0) {
            saveResults = Database.insert(trailheadEntityDeletes, false);
            DMLUtils.logErrors(saveResults, 'TrailheadEntityEventTriggerHandler');
        }
    }
}