Core/objects/TrailheadEntityDelete__c/TrailheadEntityDelete__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store information about Badges/Trails that are being archived.</description>
    <label>Trailhead Entity Delete</label>
    <nameField>
        <displayFormat>TED-{0000}</displayFormat>
        <label>Trailhead Entity Delete NumberName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Deletes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityDelete__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntityType</valueSetName>
    </valueSet>
</CustomField>

Core/globalValueSets/EntityType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>trailheadapp__Badge__c</fullName>
    </customValue>
    <customValue>
        <fullName>trailheadapp__Trail__c</fullName>
    </customValue>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record corresponds to.</description>
    <masterLabel>Entity Type</masterLabel>
</GlobalValueSet>

Core/classes/testsupport/TrailheadEntityDeleteTS.cls
@isTest
public class TrailheadEntityDeleteTS extends TestSupport.DataGeneration {
    /**
     * No arg constructor
     */       
    public TrailheadEntityDeleteTS() {
        this(new Map<String, Object>(), new List<TestSupport.TestDataField>());
    }

    /**
     * Constructor with configuration options
     * @param options 
     */
    public TrailheadEntityDeleteTS(Map<String, Object> options) {
        this(options, new List<TestSupport.TestDataField>());
    }

    /**
     * Overridden constructor with custom field specs
     * @param options DataGeneration options
     * @param fieldSpecs Custom field specs
     */    
    public TrailheadEntityDeleteTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.SOBJECT_TYPE = 'TrailheadEntityDelete__c';
    }

    protected override Map<Schema.SObjectField, TestSupport.TestDataField> loadDefaultSpecsByField() {
        return new Map<Schema.SObjectField, TestSupport.TestDataField> {
            TrailheadEntityDelete__c.APIName__c => new CounterSuffixField(TrailheadEntityDelete__c.APIName__c, 'Test_Delete_'),
            TrailheadEntityDelete__c.EntityType__c => new RandomPicklistValueField(TrailheadEntityDelete__c.EntityType__c)
        };
    }
}