Core/objects/TrailheadEntityEvent__e/TrailheadEntityEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event fired when a the values of one or more tracked fields on a Badge or Trail is updated.</description>
    <label>Trailhead Entity Event</label>
    <pluralLabel>Trailhead Entity Events</pluralLabel>
</CustomObject>

Core/objects/TrailheadEntityEvent__e/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that event corresponds to.</description>
    <label>Entity Type</label>
    <length>22</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityEvent__e/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/TrailheadEntityUpdate__c.object-meta.xml
<CustomObject>
    <description>Custom object used to store the changed values of one or more watched fields on a Badge or Trail.</description>
    <label>Trailhead Entity Update</label>
    <nameField>
        <displayFormat>TEU-{000000}</displayFormat>
        <label>TrailheadEntityUpdate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trailhead Entity Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Core/objects/TrailheadEntityUpdate__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>Value of trailheadapp__API_Name__c field on trailheadapp__Badge__c or trailheadapp__Trail__c. Used as an external ID field for integration.</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/EntityType__c.field-meta.xml
<CustomField>
    <fullName>EntityType__c</fullName>
    <description>Type of Trailhead entity (trailheadapp__Badge__c or trailheadapp__Trail__c) that record relates to updates of.</description>
    <label>Entity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>trailheadapp__Badge__c</fullName>
            </value>
            <value>
                <fullName>trailheadapp__Trail__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/objects/TrailheadEntityUpdate__c/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <description>List of fields that were changed on trailheadapp__Badge__c or trailheadapp__Trail__c.</description>
    <label>Updated Fields</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Description__c</fullName>
            </value>
            <value>
                <fullName>Icon__c</fullName>
            </value>
            <value>
                <fullName>Level__c</fullName>
            </value>
            <value>
                <fullName>Name__c</fullName>
            </value>
            <value>
                <fullName>Products__c</fullName>
            </value>
            <value>
                <fullName>Type__c</fullName>
            </value>
            <value>
                <fullName>URL__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Core/classes/testsupport/TrailheadEntityEventTS.cls
@isTest
public class TrailheadEntityEventTS extends TestSupport.DataGeneration {
    /**
     * Determines if UpdatedFields__c value is generated before each call to generate().
     */    
    public Boolean generateUpdatedFields {get; set;}

    /**
     * Holds Trailhead Entity Events by API name.
     */
    public Map<String, TrailheadEntityEvent__e> eventsByAPIName {
        get {
            if(this.eventsByAPIName == null) {
                this.eventsByAPIName = new Map<String, TrailheadEntityEvent__e>();
                for(sObject record : this.records) {
                    this.eventsByAPIName.put(String.valueOf(record.get('APIName__c')), (TrailheadEntityEvent__e) record);
                }
            }
            return this.eventsByAPIName;
        }
        set;
    } 

    /**
     * Default constructor
     * @param options DataGeneration options
     */
    public TrailheadEntityEventTS(Map<String, Object> options) {
        this(options, new List<TestSupport.TestDataField>());
    }

    /**
     * Overridden constructor with custom field specs
     * @param options DataGeneration options
     * @param fieldSpecs Custom field specs
     */
    public TrailheadEntityEventTS(Map<String, Object> options, List<TestSupport.TestDataField> fieldSpecs) {
        super(options, fieldSpecs);
        this.S_OBJECT_TYPE = 'TrailheadEntityEvent__e';
        this.generateRecordIDs = false;
        this.generateUpdatedFields = options.containsKey('generateUpdatedFields') ? Boolean.valueOf(options.get('generateUpdatedFields')) : true;
    }

    protected override Map<Schema.SObjectField, TestSupport.TestDataField> loadDefaultSpecsByField() {
        return new Map<Schema.SObjectField, TestSupport.TestDataField> {
            TrailheadEntityEvent__e.APIName__c => new CounterSuffixField(TrailheadEntityEvent__e.APIName__c, 'Test_Entity_'),
            TrailheadEntityEvent__e.EntityType__c => new ControlledValueField(
                TrailheadEntityEvent__e.EntityType__c,
                PicklistValueManager.getFieldValues(TrailheadEntityUpdate__c.getSObjectType(), TrailheadEntityUpdate__c.EntityType__c)
            )
        };
    }


    public override List<sObject> generate() {
        if(this.generateUpdatedFields) {
            List<String> updatedFields = new List<String>();
            List<String> trackedFields = PicklistValueManager.getFieldValues(TrailheadEntityUpdate__c.getSObjectType(), TrailheadEntityUpdate__c.UpdatedFields__c);
            String fieldName;
            for(Schema.SObjectField field : this.specsByField.keySet()) {
                fieldName = field.getDescribe().getName();
                if(trackedFields.contains(fieldName)) {
                    updatedFields.add(fieldName);
                }
            }
            this.setFieldSpec(new TestSupport.TestDataField(TrailheadEntityUpdate__c.UpdatedFields__c, String.join(updatedFields, ';')));
        }
        return super.generate();
    }
}